### ISSUE TITLE
A periodic button

### ISSUE THREAD

**Issue by Kiroto** [Kiroto/sumadora#1]
The program wouldn't allow me to insert periods in the variables.

**Comment by iajrz** [comment]
You don't need a period in the variable name. What are you trying to do?0

**Comment by Kiroto** [comment]
I want this to work: "123" + "."
It won't.

**Comment by iajrz** [comment]
The issue is not the name of the button; remember you're adding the dot, then converting the number (in this case "123.") into a floating point number using Convert.toSingle(). The thing is that "123." either is not a valid number, or is number 123. You need to either change the way your program works with the numbers (from float-to-string-to-float and storing in a float variable to something like "string-to-float-to-string and storing it in a string variable while operating with floats) OR treat the "." button differently than you treat the number buttons.

The first is more work (rethinking the whole program), the second introduces a special case into your already working code.
